### ISSUE TITLE
Migrate from django-celery and keep older results

### ISSUE THREAD

**Issue by mauroka** [celery/django-celery-results#24]
Hello.
I am trying to migrate from django-celery to django-celery-results.
Django-celery-results is working just fine. But the older results kept in the database in the table celery_taskmeta weren't migrated automatically to django-celery-result table.
Should I do it manually or there is something that I am missing?

Thanks a lot for the help.
Mauro.

**Comment by wardal** [comment]
Hi @mauroka . I think you need to migrate your data manually between those 2 tables. If you need we can try to make PostgreSQL (or MySQL?) script to migrate data from old table to new django-celery-results table.

**Comment by mauroka** [comment]
Hi @wardal. I'll let you know if a need help form the migration script in PostgreSQL.
Thanks a lot.

**Comment by fproldan** [comment]
Hi @wardal 

We have made an SQL migration from djcelery to django-celery-results but we are facing one problem with the ```meta``` field.

In djcelery the value is decoding with pickle to something like this:
```eJxrYKotZIzgYGBgSM7IzEkpSs0rZIotZA5VsTRKSTSytEjUNTNJNdM1MTMw001MSknVTU02MTAzSzQxTjQxKGTxa/NrK2RNLNYDAMOfE9s=```

While django_celery_results_taskresult expected something like:
```{""children"": [[[""92da298a-64e6-4606-abde-ec4066a43a40"", null], null]]}```

If I decode this value in order to save it in the django_celery_results_taskresult table I get a different structure from djcelery:
```{u'children': [(('92da298a-64e6-4606-abde-ec4066a43a40', None), None)]}```

Any ideas to solve this besides parsing the data?

Thanks a lot.
