### ISSUE TITLE
Cannot save GroupResult

### ISSUE THREAD

**Issue by helloagain-dev** [celery/django-celery-results#40]
I want to run multiple jobs as a group and want to store the result to watch the progress of the combined job.
According to the documentation I can use [GroupResult.save](http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.GroupResult.save) and restore it later.

When I try to do that I get the following error message:
```
ERROR	2017-11-10 09:05:26,293 exception 7586 139766003652352 Internal Server Error:
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "venv/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "venv/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "venv/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", line 78, in post
    async_result.save()
  File "venv/lib/python3.6/site-packages/celery/result.py", line 833, in save
    return (backend or self.app.backend).save_group(self.id, self)
  File "venv/lib/python3.6/site-packages/celery/backends/base.py", line 386, in save_group
    return self._save_group(group_id, result)
AttributeError: 'DatabaseBackend' object has no attribute '_save_group'
```

This makes sense as `django_celery_results.backends.database.DatabaseBackend` does not implement this method. `celery.backends.database.DatabaseBackend` Implements it but it is not used when set `CELERY_RESULT_BACKEND = 'django-db'`.

Did I configure this incorrectly or is this simply not implemented?

What I want to do is return the task_id of the group when a combined job is submitted and then poll the status of the group to see when all tasks are finished and not check every sub-task individually.

**Comment by busla** [comment]
Dealing with a similar issue, although I get an error on `_restore_group`. I´ll post this as a comment here since I think these two issues are related.

```
AttributeError: 'DatabaseBackend' object has no attribute '_restore_group'
```

From my DRF view:

```python
class ProgramList(generics.ListCreateAPIView):
    queryset = Program.objects.all()
    serializer_class = ProgramListSerializer

    def list(self, request):
        queryset = self.get_queryset()
        serializer = ProgramListSerializer(queryset, many=True)
        tasks = []

        for v in serializer.data:
            try:
                result = GroupResult.restore(v['task_id'], app=current_app)
            except TypeError:
                return Response({'tasks': [], 'results': serializer.data})
            else:
                if result:
                    async_results = [str(x.result)
                                     if isinstance(x.result, Exception)
                                     else x.result
                                     for x in result]
                    tasks.append(async_results)

        return Response({'tasks': tasks, 'results': serializer.data})
```

**Comment by rmad17** [comment]
I would like to solve this issue. @ask  can you give me any idea how this can be solved for django model? I see SQLAlchemy has a way to store python objects.

**Comment by auvipy** [comment]
could you try the master branch?

**Comment by daughterlycare** [comment]
Has this been solved yet?

**Comment by scnerd** [comment]
+1. Sounds like it's already fixed, but would be willing to contribute some elbow grease to fixing it if not.

**Comment by yourcelf** [comment]
I'm still hitting this issue with master branch of `django-celery-results` when using `CELERY_RESULT_BACKEND = "django-db"`.

It looks like `django_celery_results.backends.database.DatabaseBackend` inherits from `celery.backends.base.BaseDictBackend`, and neither class implements `_save_group` or `_restore_group`.  (By contrast, the cache backend inherits from `KeyValueStoreBackend` which _does_ implement those methods.)

This means that the `GroupResult` returned from `group([task.s()]).apply_async()` cannot be persisted and retrieved later, i.e. in a separate request response cycle, using `GroupResult.save()` and `GroupResult.retrieve(...)`.

So in order to asynchronously track progress of a group, it's currently necessary to either implement a different backend which defines `_save_group` and `_restore_group`, or save the ID's of the child tasks in some other model or store and check each task's status using `AsyncResult`.

Not sure why this issue was closed; but if fixing this isn't on the roadmap perhaps documentation should be updated to clarify that the `django-celery-results` db backend can't persist or retrieve group results.

**Comment by fproldan** [comment]
Hello.

Is it feasible to implement the ```_save_group``` and ```_restore_group``` methods in the ```DatabaseBackend``` class?

If so, I can help by doing a PR.

Thanks

**Comment by auvipy** [comment]
need proper unit test as well

**Comment by ngbruna** [comment]
Hello @auvipy! Are you working in this implementation? Thanks!

**Comment by AlecTroemel** [comment]
This issue is pretty old, but I'm in the process of working on it.

Do you all think the `GroupResult` should have its own Django Model? Or should it be stored in the existing `TaskResult` model?

**Comment by vesnikos** [comment]
@AlecTroemel I have it as a different model, as I wanted to capture the kwargs/args that generated that `GroupResult` and the state  of the GroupResult (when started, finished, failed etc..)

**Comment by AlecTroemel** [comment]
@vesnikos I agree with the separate models. Do you already have a fork/implementation of this? I'd like to not redo someone else's work if possible :smile:

**Comment by fproldan** [comment]
@AlecTroemel @vesnikos Hi! I'm also interested if there is any fork or implementation of this feature. We can join forces on this. :smiley:

**Comment by mattiasa** [comment]
We have an implementation of this that uses PickledObjectField to store the result. I'm not sure if that's something you would want upstream but feel free to use it if it is suitable.

https://github.com/celery/django-celery-results/compare/master...CantemoInternal:cantemo

**Comment by AlecTroemel** [comment]
@fproldan @mattiasa great! you can find [my messy WIP fork here](https://github.com/mirusresearch/django-celery-results). 

Here are the things I think we need to work through
1. __Name of the group result model:__ I went with `GroupResult` while mettiasa's implementation uses `TaskSetMeta`
2. __How to serialize the group results "results" field:__ I'm a little weary using pickle.  Since "results" is just a list of `AsyncResult`'s, maybe we could use the same encoding this package uses for that. Specifically something like this

```python
# inside /backends/database.py
def _save_group(self, group_id, group_result):
        """Store return value of group"""
        content_type, content_encoding, result_to_save = self.encode_content([r.result for r in group_result])
        self.GroupModel._default_manager.store_group_result(
             content_type, content_encoding, group_id, result
         )
        return group_result
```
3. Can there be any sort of foreign key relation between the saved `TaskResult` and `GroupResult`? Do we want that if it is possible?

I'm glad to see movement on this, thanks for the help everyone!

**Comment by auvipy** [comment]
please leave your review comments on https://github.com/celery/django-celery-results/pull/161
