### ISSUE TITLE
Allow For Filtering Of Custom Task State In Admin

### ISSUE THREAD

**Issue by ndibari-sp** [celery/django-celery-results#92]
In the django_celery_results Django admin interface, there is an option to filter by task state. This allows one to quickly see all task results that are in a particular state, like seeing all the FAILURE tasks or RETRY tasks. This only allows one to filter by the default celery states, so if you have any custom states in your database (in the case you manually call the backend.store_result method with a custom state) you won't be able to filter on the special state.

Can we add some logic in the admin view to "know" about the different states in the database and allow for filtering on any valid (existing) state for the TaskResult table? We could write a custom filter for the `status` field that does a query on the TaskResult table to find all distinct `status` options and use that list for filtering.

**Comment by liquidpele** [comment]
The state field on the model uses the choices kwarg and the options are defined by celery here:  https://github.com/celery/celery/blob/master/celery/states.py

You shouldn't be saving any choices beyond what is represented by those choices, otherwise any form/api validations will fail as it validates the django field definition.
